language: julia
os: linux
dist: bionic
julia:
  - 1
  - 1.3
  - 1.4
  - 1.5
  - nightly
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
env:
  global:
    - PYTHON=""
after_success: |
  julia -e '
    using Pkg
    Pkg.add("Coverage")
    using Coverage
    Codecov.submit(process_folder())'
